[package]
name = "zed_ocaml"
version = "0.1.7"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/ocaml.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
